aseprite/laf

- third_party/CMakeLists.txt
Save some time during compilation and exclude unnecessary test framework when LAF_WITH_TEST=OFF
> Exclude gtest if LAF_WITH_TEST is disabled

- os/osx/native_dialogs.mm
Please refer to the commits for details. I have tested this on macOS 10.13.5, and everything about native dialogs and menus look fine now. (Refer to aseprite/aseprite#2037.)
On a sided note, I cannot reproduce aseprite/aseprite#1917, but it seems a related issue and I suppose it should be looked into.
Thanks for the effort and time! ^ ^
> Fix incorrect behaviour of macOS native dialogs

- gfx/packing_rects.cpp
- gfx/packing_rects.h
- gfx/packing_rects_tests.cpp
I included a simple test, which has already helped me catch a bug ^ ^
Combined with aseprite/aseprite#2045, this tries to address aseprite/aseprite#1240.
Hope it helps!
> Extend rectangle packing algorithm with padding support

- os/osx/native_dialogs.mm
The dialogue should keep the extension if it's among the allowed ones, or append the first one in the allowed list to the file name otherwise. Closes aseprite/aseprite#1835.
For some reason `setAllowedFileTypes:` overwrites the extension provided in `setNameFieldStringValue:`, so it needs to be done before the latter. Apparently [authors of electron have run into the same issue](https://github.com/electron/electron/blob/34c4c8d5088fa183f56baea28809de6f2a427e02/shell/browser/ui/file_dialog_mac.mm#L179)... Does this count as an upstream bug in AppKit? (=~=)
> Keep supplied extension in macOS save dialogues

- os/osx/app.mm
- os/osx/app_delegate.h
- os/osx/app_delegate.mm
Closes aseprite/aseprite#1973.
I was sure this could not be achieved with an application delegate; an invisible menu would solve the problem, but might be quite cumbersome. Thus I ended up copying much code in [this StackOverflow post](https://stackoverflow.com/a/3176930) and it worked nicely.
I'm not sure whether this is the right way to name ("OSX" + "NS" looks unnecessary, but there is already an "OSXApp") and place the inherited class, so please specify if anything is to be changed. Thanks!
> Fix macOS dialogues not responding to Cmd-AZXCV

- os/win/wintab.cpp
workaround for cases where wintab report the tablet id string length incorrectly
> workaround for wintab reporting wrong id length

- gfx/hsv.cpp
- gfx/hsv.h
Before this fix the hue set function clamped the hue value between 0 and 360, instead of convert the hue value to an equivalent angle between 0 and 360.
I agree that my contributions are licensed under the Laf license, and agree to future changes to the licensing.
> Fix hue set function.

- os/x11/xinput.h
See aseprite/aseprite#2755. Version of #27 for main branch.
I agree that my contributions are licensed under the Laf license, and agree to future changes to the licensing.
> X11 error when glibc bounds checks enabled (main branch)

- base/fs.h
- base/fs_unix.h
- base/fs_win32.h
Adds a new copy_file function. This PR adds only the Windows based implementation. Linux and macOS implementations throw exception.
> Add copy_file function and its windows implementation

- os/x11/window.cpp
- os/x11/window.h
As spoken in https://github.com/aseprite/aseprite/pull/4063 - currently, if we try to bind a key to mouse trigger button and we will try to draw with it - after a longer period of holding the key, drawing will stop and will try to draw continously with short breaks.
This is caused because we never set repeat count inside the event that we generate from the event that comes from X Window System.
Repeat count is being properly checked in doc_view.cpp:onProcessMessage method, although it always equals 0 - thus allowing for the key event to be converted to mouse event, and at the same time interpreting (and queueing) it as a mouse event.
Solution for that is to simply check if the previous key event that came was KeyPress, and if it is currently pressed. If yes - it means that user never …
> Fix: Drawing using a keyboard key on X11

- os/x11/native_dialogs.cpp
Mouse clicks are ignored when we open a pipe to zenity without flushing the pending X11 events first because popen stalls aseprite execution until we selected a file.
This is in response to https://github.com/aseprite/aseprite/issues/3974
I agree that my contributions are licensed under the MIT License.
You can find a copy of this license at https://opensource.org/licenses/MIT
> Flush pending events before opening pipe to zenity

- os/draw_text.cpp
> Fix first glyph clipping when drawing text with FreeType fonts

- examples/allevents.cpp
- os/osx/view.mm
- os/win/window.cpp
- os/x11/window.cpp
Implements pending work needed for https://github.com/aseprite/aseprite/issues/131
> Add mouse coordinates to os::Event::DropFiles event indicating the point where the drop of files took place on the target window

- base/fs.cpp
- base/fs.h
- base/fs_tests.cpp
This PR introduces the get_relative_path function, which computes the relative path from a given base path to a specified file. The function signature is as follows:
```cpp
std::string get_relative_path(const std::string& filename, const std::string& base_path);
```
The get_relative_path function takes two parameters:
- filename: The absolute path of the target file.
- base_path: The absolute path of the base directory.
The function returns a string representing the relative path from base_path to filename. This is useful in scenarios where relative paths are needed for portability, readability, or other path manipulations.
Below are some examples demonstrating how to use the get_relative_path function:
```cpp
std::string filename = "/home/user/projects/my_project/src/main.cpp"; …
```
> Add get_relative_path() to base filesystem methods

- os/paint.h
- os/skia/skia_surface.cpp
- os/skia/skia_surface.h
This can be used to fix:
https://github.com/aseprite/aseprite/issues/4317
From SkCanvas::SrcRectConstraint docs:
"SrcRectConstraint controls the behavior at the edge of source
SkRect, provided to drawImageRect() when there is any filtering. If
kStrict is set, then extra code is used to ensure it nevers samples
outside of the src-rect. kStrict_SrcRectConstraint disables the
use of mipmaps."
We were always using kStrict, which disabled mipmaps.
> New Paint::SrcEdges to enable mipmaps

- base/fs.cpp
- base/fs.h
- base/fs_tests.cpp
- base/fs_unix.h
- base/fs_win32.h
Several refactors in this commit:
- Moved is_path_separator() function and path_separator as a constexpr to the header file
- Added path_separators string (for Windows, which includes \ and /)
- get_canonical_path() works only when the file exists (returns an empty string in other case)
- normalize_path() and get_absolute_path() work in a lexical level, handling only strings and getting the current path when needed, but without checking the existence of the file
Fix #98
> Fix get_canonical/absolute/normalize_path() functions

- os/osx/event_queue.h
- os/osx/event_queue.mm
Fix #89
This is the second attempt to fix the issue. This time I just used a mutex to avoid the issue and kept almost all the code in its original form. I didn't use the concurrent queue mutex to avoid polluting its API and because I'm not sure it would be enough. Hence, if at the end the concurrent queue mutex is not going to be used I believe that we should replace that queue for a regular std::deque.
> [osx] Fix events handling

- gfx/rect.h
- gfx/rect_tests.cpp
I need these methods to implement https://github.com/aseprite/aseprite/pull/4533
I have also added tests for them.
I'm not sure if you @dacap want this to be added here in laf. So let me know if you think I should move them to some aseprite utilities methods.
Maybe we can keep the sliceV and sliceH methods and move the nineSlice method. Idk whatever you say is okay.
> Add gfx::RectT slicing methods

- text/skia_font.cpp
- text/skia_text_blob_shaper.cpp
- text/text_blob.cpp
- text/text_blob.h
Fixes Skia crashes on Windows by using different bounds calculations and a more complete shape() function call.
> Improve skia text shaping & bounds calculation

- os/osx/dnd.mm
- os/win/dnd.cpp
The variable used as the return value of the function had an undefined initial value which lead to unpredictable return values. 
Also took the chance to refactor a couple of lines of code.
> Fix as_nsdragoperation

- base/fs.h
- base/fs_tests.cpp
- base/fs_unix.h
- base/fs_win32.h
As part of my work on [#4610](https://github.com/aseprite/aseprite/issues/4610) I've added directory/file filtering and pattern matching to `base::list_files` and made some optimizations and other changes:
* Now avoids allocations as much as possible
* Uses `FindFirstFileEx` on Windows which has flags to get directories directly and returns a more basic structure.
* Uses `fnmatch` on Unix to replicate the wildcard matching Windows behavior
This allows us to use list_files much more efficiently, since before you had to do:
```cpp
for (auto& item : base::list_files(path)) {
if (base::is_file(base::join_path(path, item)) && base::get_file_extension(item) == "png")
do_something(item);
}
```
which caused file attributes to be fetched twice, once when listing and another time when calling …
> Add list_files filtering

- os/osx/view.h
- os/osx/view.mm
On macOS receive dragging events only when mouse is moved while dragging is in progress, and not periodically.
> Disable periodic dragging updates

- os/dnd.cpp
- os/dnd.h
- os/win/dnd.cpp
This is useful in Windows to let the application set this function to decode webp data present when some applications provide it when dropping some element (like Chrome does when dragging&dropping an image from a result page).
> Add possibility to set a webp decoding function

- os/osx/window.mm
> [osx] Fix window's setVisible(true)

- os/win/window.cpp
- os/win/window.h
- os/window_spec.h
An option to disable WinTab for certain windows to avoid crashes from https://github.com/aseprite/aseprite/issues/3358
> [win] Add option to disable WinTab for certain windows

- base/split_string.cpp
- base/split_string.h
- base/split_string_tests.cpp
Adds a string_view version of `base::split_string`
Benchmarked difference between the two versions of the function puts the string_view version at around 36-37% faster, although it wasn't extensive testing, just a little microbenchmark:
```cpp
auto t0 = std::chrono::high_resolution_clock::now();
{
const std::string_view string = "Hello,World";
for (int i = 0; i < 200000; i++) {
std::vector<std::string_view> result;
base::split_string("Hello,World", result, ",");
}
}
auto t1 = std::chrono::high_resolution_clock::now();
auto view = std::chrono::duration_cast<std::chrono::microseconds>(t1 - t0).count();
t0 = std::chrono::high_resolution_clock::now();
{
const std::string string2 = "Hello,World";
for (int i = 0; i < 200000; i++) {
std::vector<std::string> result;
base::split_string(string2, …
```
> Add a string_view variant of base::split_string()

- os/common/system.cpp
- os/win/window.cpp
Regression introduced in 3bea53125ccafce878d17fcf8d9d192ad69fafb4, when os::instance() was refactored to os::System::instance() to return a SystemRef instead of a System*, and ~WindowWin() destructor asks for the current system() (and WindowWin::system() is trying to create a new System reference, but the System is being destroyed as it was completely unreferred, i.e. ref=0.)
> Don't add new ref to the System instance which is being destroyed (fix aseprite/aseprite#4811)

- os/osx/window.mm
- os/osx/window_delegate.h
- os/window_spec.h
This fix is the first step to solve issue aseprite/aseprite#4561
> Add modal window treatment to macOS

- os/x11/window.cpp
Fix aseprite/aseprite#3737
The issue is reproducible on KDE x11, Dolphin file manager. Drag & Drop keeps opening the same file.
Passing the time stamp from the `XdndDrop` event to `XConvertSelection` fixes the issue.
This can be useful as reusing the same window to open documents is still not supported on Linux.
I agree that my contributions are licensed under the MIT License.
> [x11] Fix drag & drop receiving incorrect file with some file managers

- base/fs.cpp
- base/fs_tests.cpp
Part of https://github.com/aseprite/aseprite/issues/4851
> Fix base::get_absolute_path() fixing base::normalize_path() function

- os/osx/app_delegate.mm
- os/osx/window.h
- os/osx/window.mm
This PR is based on the work of PR #113 and fixes the same issues: 
Fix aseprite/aseprite#4265
Fix aseprite/aseprite#4774
The difference between both PRs is on how they locate the floating windows to manipulate some of their properties.
> [osx] Mimic Windows OS's floating windows behavior

- base/task.cpp
- base/task.h
- base/thread_pool.cpp
- base/thread_pool.h
This PR introduces a couple of features to base::task:
- Possibility to set a new "done" callback that is called when the task completed its execution (we can change the name to completed instead of done if it makes more sense)
- New "enqueued" status, which is true when the task has been started but it is waiting in the thread pool's queue until the actual time to execute the function comes. 
- New "try_skip" method, which enables the caller to remove tasks from the queue that wasn't started yet.
This was introduced to be able to do some things in https://github.com/aseprite/aseprite/pull/5037. Like being able to redraw the "Running Scripts" window as needed (when a task is started/done) and to avoid showing the "stop" button for enqueued tasks. Because we can't dequeue tasks (this …
> New base::task features

- base/fs.cpp
- base/fs.h
- base/fs_tests.cpp
- base/fs_unix.h
- base/fs_win32.h
Part of the solution of issue aseprite/aseprite#5066
> Add 'is_absolute_path()' function

- os/win/window.cpp
- os/win/window.h
Fixes [#5018](https://github.com/aseprite/aseprite/issues/5018), I'm not 100% sold on the exact flag method or variable names, but the fix is sound.
Here's a video showing the change (recorded at 120 fps, then slowed down 5x)
Before:
https://github.com/user-attachments/assets/0cd4f1c1-be10-4710-aea3-03d475f9b158
---
After: 
https://github.com/user-attachments/assets/bee59769-a0f5-4607-b8c4-7493518d2895
> [win] Use SW_SHOWMAXIMIZED when first showing a maximized window (fix #5018)

- cmake/FindSkia.cmake
Related to the issue raised in https://github.com/aseprite/aseprite/pull/5071 and some CI compilation errors due to new cmake versions deprecating cmake 3.5 policies.
> Update zlib library (when it's compiled as an external project)

- text/font.h
- text/font_hinting.h
- text/freetype_font.cpp
- text/freetype_font.h
- text/skia_font.cpp
- text/skia_font.h
- text/sprite_sheet_font.h
I agree that my contributions are licensed under the MIT License.
You can find a copy of this license at https://opensource.org/licenses/MIT
I was looking at https://github.com/aseprite/aseprite/issues/4931, and found the issue could be fixed when this adding after the following line:
https://github.com/aseprite/laf/blob/cc62448d580bd415c9e7259b99ac1986ed7c4212/text/skia_text_blob_shaper.cpp#L125
`skFont.setHinting(SkFontHinting::kNone);`
However, I assume we do not want hinting to be disabled by default / all the time. So this MR is setting up the necessary API for hinting to be configurable through the Aesprite app (I imagine through the top bar when the Text Tool is used).
> Add configurable font hinting API

- os/osx/app.mm
- os/osx/app_delegate.h
- os/osx/app_delegate.mm
- os/system.h
By calling [NSApplication run] and then [NSApplication stop] we are able to initialize the application instance and prevent issues in fullscreen mode (fix aseprite/aseprite#4795)
> Fix NSApplication initialization to prevent some issues on macOS

- os/skia/skia_surface.cpp
- os/surface.h
Introduced to fix the "Avoid creating a temporal surface in static WEBP_CSP_MODE colorMode()..." item from https://github.com/aseprite/aseprite/issues/4777
> Add method to get the native color channels order

- os/skia/skia_window_osx.h
- os/skia/skia_window_osx.mm
The SkiaWindowOSX::paintGC was using integer units to calculate the scaled size portion of the source image that had to be updated. This caused that for odd rect sizes when using an even scale the rendering was offset by one pixel (one sub-pixel actually when scale was 2 for instance).
For reference: this issue was reported in a comment from another issue: https://github.com/aseprite/aseprite/issues/5095#issuecomment-2815292686
Steps to reproduce the issue:
1) Having the following settings:
Screen scaling: 200%
UI elements scaling: 100%
2) Snap the main window to the top of the screen (the right corner should do it as well).
3) Unsnap the window by dragging it from its title bar (this is the "interesting" part...unsnapping the window will make it have an odd size, not the size it had …
> [osx] Fix scaling issues when painting dirty areas

- gfx/size.h
* To add/subtract a Border to a Size
* To union/intersect two sizes
> Add some gfx::Size operators

- misc/platform.sh
Arch-based systems don't provide the `arch` command by default.
This patch falls back to `uname -m`, which gives the same result, to
ensure compatibility without affecting other distributions.
Fixes aseprite/laf#143
I agree that my contributions are licensed under the MIT License.
You can find a copy of this license at https://opensource.org/licenses/MIT
> [x11] Fallback to `uname -m` if `arch` is not available

- text/skia_font.cpp
- text/skia_font_mgr.cpp
- text/skia_font_mgr.h
This looks like an issue with DWrite, but might be a problem on other platforms as well. Might fix: https://github.com/aseprite/aseprite/issues/5233
> Avoid crash when a thread access SkTypeface::fontStyle and other one SkFontStyleSet::matchStyle
